export const UPDATE_EXPERIENCE_DATA = 'UPDATE_EXPERIENCE_DATA';
export const ADD_EXPERIENCE_DATA = 'ADD_EXPERIENCE_DATA';
export const DELETE_EXPERIENCE_DATA = 'DELETE_EXPERIENCE_DATA';
export const UPDATE_CURRENT_EXPERIENCE_DATA = 'UPDATE_CURRENT_EXPERIENCE_DATA';
export const DELETE_CURRENT_EXPERIENCE_DATA = 'DELETE_CURRENT_EXPERIENCE_DATA';
